### ISSUE TITLE
Download error with docker

### ISSUE THREAD

**Issue by jahdoos** [nf-core/fetchngs#23]
When I run with -profile docker the pipeline uses a 2.7 python version that produces this error:
`Error executing process > 'NFCORE_FETCHNGS:FETCHNGS:SRA_IDS_TO_RUNINFO (PRJNA79595)'

Caused by:
  Process `NFCORE_FETCHNGS:FETCHNGS:SRA_IDS_TO_RUNINFO (PRJNA79595)` terminated with an error exit status (1)

Command executed:

  echo PRJNA79595 > id.txt
  sra_ids_to_runinfo.py \
      id.txt \
      PRJNA79595.runinfo.tsv \

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/rfor10/.nextflow/assets/nf-core/fetchngs/bin/sra_ids_to_runinfo.py", line 170, in <module>
      sys.exit(main())
    File "/home/rfor10/.nextflow/assets/nf-core/fetchngs/bin/sra_ids_to_runinfo.py", line 167, in main
      fetch_sra_runinfo(args.FILE_IN, args.FILE_OUT, ena_metadata_fields)
    File "/home/rfor10/.nextflow/assets/nf-core/fetchngs/bin/sra_ids_to_runinfo.py", line 133, in fetch_sra_runinfo
      for row in csv_dict:
    File "/opt/conda/lib/python2.7/csv.py", line 108, in next
      row = self.reader.next()
  UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 778: ordinal not in range(128)`

Either running locally, or without docker which have python 3.8 in path runs fine with no errors.

**Comment by prmac** [comment]
Docker image requires python 3.8.
